/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package utcn.repoviewer;

import java.awt.*;
import java.io.File;
import java.time.Clock;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.plaf.SplitPaneUI;
import javax.swing.plaf.basic.BasicTreeUI;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;


/**
 *
 * @author ocuibus
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneOptions = new javax.swing.JTabbedPane();
        panelChooseFolder = new javax.swing.JPanel();
        textFieldRootFolder = new javax.swing.JTextField();
        labelCurrentFolder = new javax.swing.JLabel();
        buttonChooseRootFolder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList<>();
        panelView = new javax.swing.JPanel();
        scrollPaneFolderSelect = new javax.swing.JScrollPane();
        treeFolders = new javax.swing.JTree();
        panelViewCode = new javax.swing.JPanel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repo Viewer");

        tabbedPaneOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbedPaneOptionsMouseClicked(evt);
            }
        });

        textFieldRootFolder.setEditable(false);
        textFieldRootFolder.setText("select folder");
        textFieldRootFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldRootFolderMouseClicked(evt);
            }
        });

        labelCurrentFolder.setText("current folder");

        buttonChooseRootFolder.setText("...");
        buttonChooseRootFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseRootFolderActionPerformed(evt);
            }
        });

        jListStudents.setModel(studentsList);
        jScrollPane2.setViewportView(jListStudents);

        javax.swing.GroupLayout panelChooseFolderLayout = new javax.swing.GroupLayout(panelChooseFolder);
        panelChooseFolder.setLayout(panelChooseFolderLayout);
        panelChooseFolderLayout.setHorizontalGroup(
            panelChooseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChooseFolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChooseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChooseFolderLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(185, 185, 185))
                    .addGroup(panelChooseFolderLayout.createSequentialGroup()
                        .addComponent(labelCurrentFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldRootFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonChooseRootFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(332, 332, 332))
        );
        panelChooseFolderLayout.setVerticalGroup(
            panelChooseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChooseFolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChooseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonChooseRootFolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelChooseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCurrentFolder)
                        .addComponent(textFieldRootFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textFieldRootFolder.getAccessibleContext().setAccessibleName("");
        labelCurrentFolder.getAccessibleContext().setAccessibleName("labelFolder");
        buttonChooseRootFolder.getAccessibleContext().setAccessibleName("buttonChooseFolder");

        tabbedPaneOptions.addTab("choose folder", panelChooseFolder);

        panelView.setLayout(new java.awt.BorderLayout());

        treeFolders.setModel(treeModelFoldersStructure);
        treeFolders.setRootVisible(false);
        treeFolders.setScrollsOnExpand(true);

        treeFolders.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                treeFoldersTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                treeFoldersTreeExpanded(evt);
            }
        });
        treeFolders.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeFoldersValueChanged(evt);
            }
        });
        scrollPaneFolderSelect.setViewportView(treeFolders);

        panelView.add(scrollPaneFolderSelect, java.awt.BorderLayout.WEST);

        panelViewCode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelViewCodeLayout = new javax.swing.GroupLayout(panelViewCode);
        panelViewCode.setLayout(panelViewCodeLayout);
        panelViewCodeLayout.setHorizontalGroup(
            panelViewCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        panelViewCodeLayout.setVerticalGroup(
            panelViewCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelView.add(panelViewCode, java.awt.BorderLayout.CENTER);

        tabbedPaneOptions.addTab("view", panelView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneOptions)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChooseRootFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseRootFolderActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Please choose root folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.loadStudents(chooser.getSelectedFile());
            textFieldRootFolder.setText(chooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_buttonChooseRootFolderActionPerformed

    private void tabbedPaneOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedPaneOptionsMouseClicked
        studentsToView.clear();
        studentsToView.addAll(jListStudents.getSelectedValuesList());
        if (studentsToView.size() > 0){
            String defaultStudentForFolderStructure = studentsToView.get(0);
            String absolutePathToStudentFolder = getAbsolutePathToStudent(defaultStudentForFolderStructure);
            //System.out.println("this folder was selected" + absolutePathToStudentFolder);
            // TODO: change here to get an "average" of folders structure
            File rootDirectory = new File(absolutePathToStudentFolder);
            treePopulator.populate(rootDirectory); //Here is problem, too many calls -> tree resets after some events
            treeFolders.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        }
    }//GEN-LAST:event_tabbedPaneOptionsMouseClicked

    private void treeFoldersValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeFoldersValueChanged
        //System.out.println("this path was selected: " + treeFolders.getSelectionPath());
        panelViewCode.removeAll();
        if (treeFolders.getSelectionPath() != null){
            String firstSelectedPath = treeFolders.getSelectionPath().toString();
            panelViewCode.setLayout(new GridLayout(1, studentsToView.size()));
            // add all fileviews to the panel, but only if selection is a file!
            if (((FileNode)treeFolders.getLastSelectedPathComponent()).isViewableFile){
                for (String student: studentsToView){
                    FileView studentFileView = new FileView(student, getAbsolutePathToFile(student, firstSelectedPath.toString()));
                    panelViewCode.add(studentFileView);
                }
            }
        }
        panelViewCode.revalidate();
        panelViewCode.repaint();

    }//GEN-LAST:event_treeFoldersValueChanged

    private void textFieldRootFolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldRootFolderMouseClicked
        buttonChooseRootFolderActionPerformed(null);
    }//GEN-LAST:event_textFieldRootFolderMouseClicked

    private void treeFoldersTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
        panelView.revalidate();
    }

    private void treeFoldersTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {
        panelView.revalidate();
    }
    
    private String getAbsolutePathToStudent(String studentName){
        return textFieldRootFolder.getText() + "\\" + studentName;
    }
    
    private String getAbsolutePathToFile(String studentName, String filePath){
        return textFieldRootFolder.getText() + "\\" + studentName + "\\" + filePath;
    }
    
    private void loadStudents(File rootFolder){
        studentsList.clear();
        for (File studentFolder : rootFolder.listFiles()){
            //TODO: parse student name from folder name
            //TODO: only display folders that match the pattern isp-main-name-surname-group
            if (studentFolder.isDirectory())
                studentsList.addElement(studentFolder.getName());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseRootFolder;
    private javax.swing.JList<String> jListStudents;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCurrentFolder;
    private javax.swing.JPanel panelChooseFolder;
    private javax.swing.JPanel panelView;
    private javax.swing.JPanel panelViewCode;
    private javax.swing.JScrollPane scrollPaneFolderSelect;
    private javax.swing.JTabbedPane tabbedPaneOptions;
    private javax.swing.JTextField textFieldRootFolder;
    private javax.swing.JTree treeFolders;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<String> studentsList = new DefaultListModel<String>();
    private DefaultTreeModel treeModelFoldersStructure = new DefaultTreeModel(null);
    private TreePopulator treePopulator = new TreePopulator(treeModelFoldersStructure);
    private ArrayList<String> studentsToView = new ArrayList<String>();
}
